apiVersion: apps/v1
kind: Deployment
metadata:
  name: assessment
  namespace: assessment
  labels:
    app: assessment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assessment
  template:
    metadata:
      labels:
        app: assessment
    spec:
      containers:
        - name: assessment
          image: ghcr.io/hraedon/sysadmin_competence_evaluation:857e1be63ddac08800803c3b1b01461a7da7ae38
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
